### ISSUE TITLE
plugin.video.themoviedb.helper issue

### ISSUE THREAD

**Issue by kolekan** [Goldenfreddy0703/repository.hooty#1]
Please check the link of plugin.video.themoviedb.helper jurialmunkey's repo in your repo. It is linked to nexus branch that in some cases causing depedencie failure of xbmc.python v 3.0.1 on matrix systems

**Comment by Goldenfreddy0703** [comment]
Hey there, thank you for showing me this. I didn't realize it was linked to the nexus branch. I may have to fix my repo again in the future so that it can have categories for Leia, Matrix, and Nexus.

**Comment by kolekan** [comment]
Are you planning to fix this issue?

**Comment by Goldenfreddy0703** [comment]
Oh hey, I am but been busy with alot of stuff, figured how I can make my repo work with matrix stuff so it should be easy to do. I would have to edit my script tho and all.

**Comment by Goldenfreddy0703** [comment]
Heyyyy sorry i took forever but i updated my repo to have a matrix branch so tmdb helper should work with matrix. If you have any other addons that need to be added, pls reply in this issue. I will be closing this issue now.
