### ISSUE TITLE
Request to add Open Wizard to your repo

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/repository.hooty#2]
a4k repo hasn't been updated for 20, since you have the a4ksubs, can you add open wizard as well?

**Comment by Goldenfreddy0703** [comment]
Hey sorry i did not receive your message earlier, i was thinking about adding Openwizard but i was not sure sense Openwizard is archived sadly. 
I will think about it tho. 
Thank you

**Comment by Goldenfreddy0703** [comment]
Hey so about Openwizard. i don't think im going to be adding it. Big reason why is cause its not being maintained anymore. I would maintain but too busy sadly with Otaku. 

Anyway im going to close this bug if someones decides to maintain Openwizard someday, will be happy to add it to my repo as long as its being maintained by a dev.
