### ISSUE TITLE
Repo with only Otaku?

### ISSUE THREAD

**Issue by fugkco** [Goldenfreddy0703/repository.hooty#3]
Is it possible to have a separate repo with only Otaku related things? I'm using the original repos for some of the addons included here, and it's causing lots of confusion on my part and on Kodi's part.

**Comment by Goldenfreddy0703** [comment]
Just out of curiosity but why do you think it is causing alot of confusion?

One big reason why i have other addons on here other then Otaku is cause my addons update weekly for my setups and thats why i made this repo for it. Other repos can sometime update continuously like jurialmunkey's repo which is also why i made this repo.

**Comment by Goldenfreddy0703** [comment]
Hey @fugkco are you still there by anychance?

**Comment by fugkco** [comment]
Heh, sorry, I thought I'd replied.

For starters, kodi doesn't actually know which repo the addon is coming from. E.g. even though I've installed all the addons from the official repos, it still shows that it's installed from here.

**Comment by Goldenfreddy0703** [comment]
Ohhhhhh there could probably be an addon that's from my repo. Which addon are you talking about?

**Comment by fugkco** [comment]
Many. If I go to all addons, it'll show two entries, one that's from this repo, and one from the original repo. The one that shows as installed sometimes flip flops.

I've installed all the addons from their official repos. Hooty and Otaku gets installed last because of this.

Either way, it would be great if you can separate out Otaku into its own repo so people are able to decide whether they install addons from your repo or from the official repos.

**Comment by Goldenfreddy0703** [comment]
I would but I would have to rewrite my weekly repo update scripts and everything. I think I kinda see what you mean tho and I may have to write a new script and new private repository for myself so that my addons can update weekly.

Thank you for pointing this out cause I forgot that if you install my repo your getting updated addons from developers repos and not the official kodi repo and they update automatically. 

Will provide a fix for this soon. 
Thank you

**Comment by Goldenfreddy0703** [comment]
Hey so good news, looks like it was not a pain so i made Otaku its own repo. If you like, here is the new repo. The old repo will still be online and update all my addons but if you like, you can delete my old repo and download my new repo. 

Github: https://github.com/Goldenfreddy0703/repository.otaku

# Installation & Updates

_You can install it via repository to provide automatic updates (future updates may require to rebuild database)_

- Download repository: [repository.otaku](https://github.com/Goldenfreddy0703/repository.otaku/blob/master/repository.otaku-1.0.zip?raw=true)
- Or install it via Kodi file-manager
  - add source: <https://goldenfreddy0703.github.io/repository.otaku>

**Comment by fugkco** [comment]
Awesome mate! Thank you so much :)

**Comment by Goldenfreddy0703** [comment]
Anytime, thanks for pointing this issue out.
