### ISSUE TITLE
Silvo lite skin

### ISSUE THREAD

**Issue by Arthur1967** [Goldenfreddy0703/repository.hooty#6]
That skin uses extended info And it runs pretty fast from DJ themes repo you added as an option you can add hopefully that helps

**Comment by Goldenfreddy0703** [comment]
Might be a good skin but would you mind providing some screenshots or a link to it, I'm unable to find the skin.

**Comment by Arthur1967** [comment]
https://iwf1.com/kodi/repository.djaythemes

**Comment by Arthur1967** [comment]
It also allows you to use the movie, database helper. I don’t use it, but I
seen you ask about it.

**Comment by Arthur1967** [comment]
![image](https://github.com/Goldenfreddy0703/repository.hooty/assets/69996032/4a9dbb04-f318-4d02-a42d-9afa94a79b89)

**Comment by Arthur1967** [comment]
![image](https://github.com/Goldenfreddy0703/repository.hooty/assets/69996032/735c8ead-7d6e-451c-95c4-1ab63a683786)

**Comment by Arthur1967** [comment]
![image](https://github.com/Goldenfreddy0703/repository.hooty/assets/69996032/f2e6add8-8a40-481c-8cc6-180617445171)

**Comment by Arthur1967** [comment]
https://iwf1.com/kodi/repository.funstersplace lots of skins in that too

**Comment by Arthur1967** [comment]
![image](https://github.com/Goldenfreddy0703/repository.hooty/assets/69996032/7a7a0901-048f-41fb-a78b-68de5c0307ff) he has lots of skins too

**Comment by Goldenfreddy0703** [comment]
Hey sorry i did not get to you sooner but from looking at it, im not really a big fan of it unfortunately. Im mostly a big fan of a skin that looks like the old osmc skin, something modern, simple, ect.  

Something similar to this when it was alot nicer then there new skin:
![image](https://github.com/Goldenfreddy0703/repository.hooty/assets/62456796/034b0807-cc6f-4b73-9c44-3d223301d059)

**Comment by Arthur1967** [comment]
No problem, I understand.
