### ISSUE TITLE
Make a skin

### ISSUE THREAD

**Issue by Arthur1967** [Goldenfreddy0703/repository.hooty#7]
You sound like you could make your own skin I would use it if you did

**Comment by Goldenfreddy0703** [comment]
I mean i could, but xmls would be a pain to work with. What im just gonna do is probably mess with the fen skin maybe and just get some of my favorite search engines in there and i should be good.

**Comment by Goldenfreddy0703** [comment]
Oh btw, if you like, instead of making issues, feel free to contact me anytime, my messages are always open so feel free to contact me on either discord, keybase, or even reddit. 

## Contact

Discord: The Steampunk Owl#3126

Keybase: [Goldenfreddy0703](https://keybase.io/goldenfreddy0703)

**Comment by Arthur1967** [comment]
OK, will do. Hopefully you make it so I can use the scan you make changes to.
