### ISSUE TITLE
Seren colored icons

### ISSUE THREAD

**Issue by Arthur1967** [Goldenfreddy0703/repository.hooty#8]
Using Arctic Zephyr 2 -resurrection I can't get seren icons to show what am I doing wrong

**Comment by Goldenfreddy0703** [comment]
Umm those Seren Icons in my repo are icons you have to set manually and all, main reason why I have those icons in my repo is cause hooty repo is basically just a personal repo for me. 

If your downloading thr Seren addon, you may notice that the icons are black, that's cause I changed them so they look nicer for my build.

**Comment by Arthur1967** [comment]
OK, yes I see them darker. Thank you.

**Comment by Arthur1967** [comment]
Can you point me in the right direction as to where I can download them and install them thank you. Have a good day.
